### ISSUE TITLE
Firebase Storage: Invalid argument in `put` at index 0: Expected Blob or File.

### ISSUE THREAD

**Issue by smilechun** [wkh237/rn-firebase-storage-upload-sample#3]
Once the upload statement fire, it return:
Possible Unhandled Promise Rejection (id: 0):
Firebase Storage: Invalid argument in `put` at index 0: Expected Blob or File.

Please help.

code snippet:

let images = this.state.images;
        let uri = images[0].path.uri;
        let type = uri.substr(uri.lastIndexOf('.') + 1);
        let rnfbURI = RNFetchBlob.wrap(uri);

```
    let filename = new Date().getTime().toString();

    console.log(uri, type, filename);

    // create Blob from file path
    Blob
        .build(rnfbURI, { type : 'image/' + type + ';'})
        .then((blob) => {
            console.log(blob);
            // upload image using Firebase SDK
            firebase.storage()
                .ref('users')
                .child(filename)
                .put(blob, { contentType : 'image/' + type })
                .then((snapshot) => {
                    console.log('Done.');
                    console.log(snapshot);
                    blob.close();
                })
                .catch((err) => {
                    console.log(err);
                    blob.close();
                })
        });
```

**Comment by smilechun** [comment]
The problem is solved.
I forgot to add the following statements.
window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest
window.Blob = Blob

but another error thrown:

> ExceptionsManager.js:61 Firebase Storage: An unknown error occurred, please check the error payload for server response.

After the investigation, it is the same problem as [Crashes with larger images](https://github.com/wkh237/rn-firebase-storage-upload-sample/issues/2)

**Comment by wkh237** [comment]
@smilechun , thanks for report, we're working on the issue 😄

**Comment by MrRoyce** [comment]
@smilechun where those images that you uploaded to Firebase from the CameraRoll on a device?  

I've not been able to get images from my CameraRoll to upload to Firebase.  I filed an issue here https://github.com/wkh237/react-native-fetch-blob/issues/109

**Comment by MrRoyce** [comment]
Interesting I can get the sample program to work correctly if I use it as is, but if I hardcode the file name to a file from my CameraRoll such as `file:/storage/emulated/0/DCIM/Camera/IMG_20160626_154134.jpg` , it fails with the message I reported in the other thread 

*The callback slice() exists in module RNFFetchBlob, but only one callback may be registered to a function in a native module.*
