### ISSUE TITLE
Firebase Storage Upload Not working

### ISSUE THREAD

**Issue by nmsdvid** [wkh237/rn-firebase-storage-upload-sample#8]
It seems that the example that you provided is not working anymore, I'm always getting a _Firebase Storage: Invalid argument in `put` at index 0: Expected Blob or File._ Any idea why ? Using firebase version 3.6.2 and react-native-fetch-blob 0.10.2.

**Comment by wkh237** [comment]
@nmsdvid , I've updated the project template, please clone the project and try again 👍

**Comment by nmsdvid** [comment]
Thx @wkh237 everything works as expected.
